### ISSUE TITLE
Authentication not possible under SailfishOS due to new process invoking Captchas

### ISSUE THREAD

**Issue by rgsidler** [sailfish-spotify/hutspot#111]
Despite entering the correct credentials, HutSpot complains about the authentication having failed. Restartung the app reroutes me from the simple credential entering dialog to a website, where I should follow a captcha process. This doesn't work, since it states, that my browser is not actual and therefore the authentication process could not be completed.
So I am stuck at that point, not having any option to avoid that captcha. Long speech, short conclusion: At the moment, this app unfortunately is unusable.

**Comment by wdehoog** [comment]
Sorry to hear this. I haven't tried it for a while. Other stuff prevents me from working on this soon.

**Comment by ksiazkowicz** [comment]
You can enable signing in through browser in settings AFAIK and that should work.

**Comment by rgsidler** [comment]
@wdehoog @ksiazkowicz Thank you very much for your support. I feel a bit awkward, that I didn't find the solution by myself - mea culpa :-(
Maciej, your solution worked flawlessly - I am a happy listener, again 👍
