### ISSUE TITLE
ListView should use the ViewPlaceholder

### ISSUE THREAD

**Issue by rgrnetalk** [sailfish-spotify/hutspot#14]
Observerd behavior: when the lists have no items, a small label appears at the bottom of the screen that says: "nothing found". The viewplaceholder is designed for this purpose: 
[ViewPlaceholder {
                     enabled: view.count == 0
                     text: "No items yet"
                     hintText: "Pull down to add items"
                 }](url)

It is shown at the middle of the page (and it has the non-interactive coloring, because it is not clickable).

**Comment by wdehoog** [comment]
thanks for the suggestion
