### ISSUE TITLE
Alternative icon (just to share)

### ISSUE THREAD

**Issue by rgrnetalk** [sailfish-spotify/hutspot#28]
Although one of the basic forms of the Jolla Icon set is a circle, I find the standard circle icon rather boring. Made myself a nice alternative Sailfish Spotify icon (no gradient of whatever, just a plain simple icon). (You would say I could spend my time better ;-) 
![harbour-spotify](https://user-images.githubusercontent.com/12599622/44949594-388c0400-ae35-11e8-880a-c74f56777cca.png)

**Comment by wdehoog** [comment]
It is in. Thanks.

**Comment by ksiazkowicz** [comment]
Something worth considering is, that we can't really use Spotify branding legally.

**Comment by BonoNL** [comment]
If they want us not to use it, then they should build a descent native app for SailfishOS.

And if they are giving us a hard time, maybe we should turn the picto upside down and paint it some other sailfish blue or something like that.

**Comment by rgrnetalk** [comment]
Information on Spotify logo use can be found at: [Branding guidelines](https://developer.spotify.com/branding-guidelines/). With the naming bid we're safe, but with the logo we're over the edge...

**Comment by ksiazkowicz** [comment]
![image](https://user-images.githubusercontent.com/1162358/45057569-42607200-b096-11e8-8bce-1265748e59d5.png)
new logo idea (jk)
