### ISSUE TITLE
librespot does not start at boot

### ISSUE THREAD

**Issue by wdehoog** [sailfish-spotify/hutspot#37]
When enabling the librespot service by changing the `[Install]` lines in the unit file and `systemctl --user enable librespot` it is supposed to start at boot. However this does not happen.
It keeps complaining with `ENODEV (No such device)` about the network sockets.

After logging in `systemctl --user start librespot` works though.

**Comment by ksiazkowicz** [comment]
I think this bug is more than Librespot not starting. I ran it under debugger. I set a breakpoint in start() function in Librespot.qml. It correctly detected that Librespot is not running. I stepped over - service started and I could control it from my PC. It then crashes after some request to Spotify API is made. Needs more investigation.

**Comment by wdehoog** [comment]
Could you see if it helps to disable calling 'librespot.addUser(..)' in hutspot.qml lines 416 + 534.
Maybe re-registering Librespot causes it to crash.

**Comment by wdehoog** [comment]
After enabling start at boot in the service file one still needs to execute 
```
systemctl --user disable librespot
systemctl --user enable librespot
```
so systemd handles the dependencies. 

Still start at boot will fails since there is no network. In fact it seems useless to start at boot since there probably is no network avalable at that point.

**Comment by ksiazkowicz** [comment]
Was the bug with librespot not starting with hutspot fixed?

**Comment by wdehoog** [comment]
Sorry what do you mean? This bug is original about the service file of the Librespot package.
If launching Librespot from hutspot does not work lets create a new issue.
