### ISSUE TITLE
Crash after disabling Discovery

### ISSUE THREAD

**Issue by ksiazkowicz** [sailfish-spotify/hutspot#56]
I can't see anything useful in logs, but it's easy to reproduce.

1. Open Settings
2. Enable device discovery (I also enable Librespot since it's somehow stopping on app startup, weird)
3. Exit settings (this one is pretty important)
4. Open settings again and disable device discovery

**Comment by wdehoog** [comment]
It looks like the qmdnsengine library tries to send eol messages when the server already has been destroyed. adeaeb1 fixed it for me. Could you check if it works for you as well?
