### ISSUE TITLE
Play fails

### ISSUE THREAD

**Issue by evil5hadow** [sailfish-spotify/hutspot#64]
When I try to play a track, I get "Play failed:404:Device not found".

- I am logged in into my Spotify premium account and I can browse my playlists
- I have revoked app's access and refreshed its token but still fails

Other suggestions?

Thank you

**Comment by wdehoog** [comment]
hutspot is a controller not a player. You will have to select a player from the Devices page to listen to your music. Librespot is a player and can be installed on your phone. Then if all goes well it will show up in the Device list, you can make it your current device and it will play your music.

**Comment by evil5hadow** [comment]
Got it. All good now. 
Thanks!
