### ISSUE TITLE
Light ambience messes Now Playing screen

### ISSUE THREAD

**Issue by raketti** [sailfish-spotify/hutspot#96]
The dark ambience works nicely with Hutspot, but if a light ambience is used, the Now Playing screen isn't readable. I tried looking in to the qml, but couldn't find a clear indication on where the theme is defined (total noob here), I honestly don't know if this is something that is declared for each qml file separately or if it't inherited from somewhere.

Here's some screenshots of the Now Playing screen with light ambience:
https://imgur.com/a/gc0wUjn

**Comment by ksiazkowicz** [comment]
Thanks for your feedback! I pushed a quick fix that should fix that. Have you found other issues with light ambiences? I've noticed there was a similar issue in cover page.

**Comment by raketti** [comment]
Thanks, tried the latest build and it works great now with the light ambience. Haven't noticed any other issues, but if I do I'll report accordingly.
